import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { ModalProvider } from "@/context/ModalContext";
import ContactModal from "@/components/ContactModal";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="text-[70%] lg:text-[85%]">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased font-cabin`}
      >
        <ModalProvider>
          {children} <ContactModal />
        </ModalProvider>
      </body>
    </html>
  );
}
